### ISSUE TITLE
Optimise `force()` function

### ISSUE THREAD

**Issue by lleon95** [KristerJazz/P1.9_Collaborative_Project#21]
This issue is related to the `force()` optimisation. The suggested steps are:

* Get rid of expensive operations
* Optimise the `pbs()` function calls
* Analyse data structures (without altering them yet) - do it in another branch

After each optimisation, please, create a new profile stored in: `root/docs/number-my-optimisation.md`

**Comment by mattiacmhpc** [comment]
*pbc()
